// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TokenColumns holds the columns for the "token" table.
	TokenColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt, Unique: true},
	}
	// TokenTable holds the schema information for the "token" table.
	TokenTable = &schema.Table{
		Name:       "token",
		Columns:    TokenColumns,
		PrimaryKey: []*schema.Column{TokenColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "token_user_access_token",
				Columns:    []*schema.Column{TokenColumns[4]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TokenTable,
		UserTable,
	}
)

func init() {
	TokenTable.ForeignKeys[0].RefTable = UserTable
	TokenTable.Annotation = &entsql.Annotation{
		Table: "token",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
